spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

# Neon PostgreSQL — values loaded from .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 Google Client Config
spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT Secret config
application.security.jwt.secret-key=JWT_SECRET
application.security.jwt.expiration=JWT_EXPIRATION

# Server port
server.port=8081